### ISSUE TITLE
error with lumen

### ISSUE THREAD

**Issue by 0utc0ntr0l2021** [ip2location/ip2location-laravel#4]
i used it in lumen but i get error : Class "IP2LocationLaravel" not found
i used the controller like readme
rout work but with that error

**Comment by ip2location-com** [comment]
Thank you for the input and we have taken a note about it. However, we are not supporting lumen at the moment.

**Comment by 0utc0ntr0l2021** [comment]
Ok thanks
I think it neef one line to add as service provider
