### ISSUE TITLE
PHP 8.2+ support: Deprecated:Creation of dynamic property

### ISSUE THREAD

**Issue by andreypopov** [ip2location/ip2location-laravel#5]
Please, fix this one:

Deprecated:Creation of dynamic property Ip2location\IP2LocationLaravel\IP2LocationLaravel::$db is deprecated(8192)
File: /vendor/ip2location/ip2location-laravel/src/IP2LocationLaravel.php:11
$this->db = new \IP2Location\Database($this->getDatabasePath(), \IP2Location\Database::FILE_IO);

![2023-11-28_14-14-31](https://github.com/ip2location/ip2location-laravel/assets/1624839/e5c4dce8-1649-4e43-8d49-d08d7a30c389)

**Comment by andreypopov** [comment]
PR https://github.com/ip2location/ip2location-laravel/pull/6

**Comment by ip2location-com** [comment]
Hi andrey,

We have tested our library in PHP 8.2.6 and 8.3.0 but unable to reproduce the issue. Can you please provide us:

1. Your environment, eg PHP and Laravel version?
2. The code that you have produced the issue with?

**Comment by andreypopov** [comment]
Just capture errors like:


```
<php

set_error_handler(['ErrorHandlerLaravel', 'captureNormal'], E_ALL & ~(E_STRICT));

class ErrorHandlerLaravel
{
    public static function captureNormal($number, $message, $file, $line)
    {
        $error = [
            'type' => $number,
            'message' => $message,
            'file' => $file,
            'line' => $line,
        ];
        dump($error);
    }
}

\Ip2location\IP2LocationLaravel\Facade\IP2LocationLaravel::get(request()->ip());

```

**Comment by ip2location-com** [comment]
Hi andrey,

Thanks for the reply, we will check on this deprecation message and your PR.
